# Generated by Django 2.2 on 2019-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190707_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Surname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
