# Generated by Django 2.2 on 2019-06-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='school',
            new_name='sName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='person',
            name='grade',
        ),
    ]
