# Generated by Django 2.2 on 2019-07-17 15:30

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300, null=True)),
                ('middle_name', models.CharField(max_length=300, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('intercom', models.CharField(max_length=300, null=True)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
