# Generated by Django 2.2 on 2019-07-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_batch_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='attendance.AttendancePerson'),
        ),
    ]
