# Generated by Django 2.2 on 2019-07-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190717_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceperson',
            name='address',
        ),
    ]
