# Generated by Django 2.2 on 2019-07-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0005_remove_attendanceperson_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceperson',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(to='attendance.AttendancePerson')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ClassItem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendancePerson')),
            ],
        ),
    ]
