# Generated by Django 2.2 on 2019-07-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20190718_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('scheduled_date_time', models.DateTimeField(blank=True, null=True)),
                ('execution_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=300, null=True)),
                ('batches', models.ManyToManyField(to='attendance.Batch')),
                ('students', models.ManyToManyField(to='attendance.AttendancePerson')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300, null=True)),
                ('attendance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceEvent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendancePerson')),
            ],
        ),
        migrations.RemoveField(
            model_name='classitem',
            name='students',
        ),
        migrations.DeleteModel(
            name='AttendanceList',
        ),
        migrations.DeleteModel(
            name='ClassItem',
        ),
    ]
